import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
await page.goto("http://127.0.0.1:1420/");
await page.waitForTimeout(1400);
await page.click('button[title="均衡器"]');
await page.waitForTimeout(400);
await page.screenshot({ path: "/tmp/shots/06-eq.png" });
await browser.close();
console.log("ok");
